name: Android Build

on:
  push:
    branches:
      - master  # Change this to your main branch name (e.g., master)
      - dev
      - 26-ci-is-broken
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.5

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1.2.0
        with:
          ndk-version: r25c

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Dump versions
        run: ./gradlew --version; cmake --version;ls -l; ls -l liblsl/lslboost/boost/tti/gen/namespace_gen.hpp

      - name: Build APK
        run: ls -a; ./gradlew assembleDebug  # Change 'assembleDebug' to 'assembleRelease' if you want a release build

      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-debug  # Change this to your desired artifact name
          path: ./app/build/outputs/apk/debug/LSLRecorder-1.0.0-debug.apk
